# Logging and Paths
wandb_proj: ESM2_PPI_Gold # Weights and Biases project to log results to.
wandb_save: False # Whether or not to log to Weights and Biases.
log_file: ./logs/scratch_testing.log # Location of log file
model_save_dir: ./best_models # Location to save best models
data_cache_dir: ./datasets # Location of downloaded data (use `download_data.py`)

# Misc
device: 0 # CUDA device to use for training
replicate: 12345 # Random seed
verbosity: 3 # Verbosity level for logging

# Task and Dataset
task: ppi_gold # Benchmark task - one of "davis", "bindingdb", "dti_dg", "ppi_gold"

# Model and Featurizers
drug_featurizer: MorganFeaturizer # Featurizer for small molecule drug SMILES (see `featurizer` documentation)
target_featurizer: ESMFeaturizer # Featurizer for protein sequences (see `featurizer` documentation)
target_model_type: esm2_t6_8M_UR50D # pre-trained ESM-2 model - one of "esm2_t6_8M_UR50D", "esm2_t12_35M_UR50D", "esm2_t30_150M_UR50D", "esm2_t33_650M_UR50D"
model_architecture: PPIPooling # Model architecture (see `models` documentation)
latent_dimension: 1024 # Dimension of shared co-embedding space
latent_distance: "Cosine" # Distance metric to use in learned co-embedding space
pooling: "swe" # Pooling operation to be used for target embeddings (avg or swe)
num_slices: 128 # Number of slices (only for swe pooling; ignored for avg pooling)
num_ref_points: 128 # Number of points in the reference set (only for swe pooling; ignored for avg pooling)

# Training
epochs: 50 # Number of epochs to train for
batch_size: 32 # Size of batch for binary data set
shuffle: True # Whether to shuffle training data before batching
num_workers: 0 # Number of workers for PyTorch DataLoader
every_n_val: 1 # How often to run validation during training (epochs)

## Learning Rate
lr: 1e-4 # Learning rate for binary training
lr_t0: 10 # With annealing, reset learning rate to initial value after this many epochs for binary traniing